# Generated by Django 4.2.1 on 2024-01-23 04:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="postContent",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
