# Generated by Django 3.2.1 on 2024-02-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImageAWS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
