# Generated by Django 4.2.1 on 2024-01-23 04:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_postcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="postContent",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
