# Generated by Django 4.2.1 on 2024-01-25 14:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_postcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="postContent",
            field=ckeditor.fields.RichTextField(verbose_name="Post Content"),
        ),
        migrations.AlterField(
            model_name="post",
            name="postTitle",
            field=models.CharField(max_length=200, verbose_name="Post Title"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birtday",
            field=models.CharField(max_length=200, verbose_name="Birthday"),
        ),
        migrations.AlterField(
            model_name="user",
            name="blogCount",
            field=models.IntegerField(default=0, verbose_name="Number of Blogs"),
        ),
    ]
