# Generated by Django 4.2.1 on 2024-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postPublished',
            field=models.BooleanField(default=True),
        ),
    ]
