# Generated by Django 4.2.1 on 2024-02-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_postpublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Token'),
        ),
    ]
