# Generated by Django 4.2.1 on 2024-02-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_user_id_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_token',
            field=models.TextField(blank=True, null=True, verbose_name='ID Token'),
        ),
    ]
