# Generated by Django 4.2.1 on 2024-02-18 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_user_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the platform')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire of Access Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_seq',
            },
        ),
    ]
