# Generated by Django 4.2.1 on 2024-02-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_user_access_token_remove_user_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='line_id',
            field=models.TextField(blank=True, null=True, verbose_name='Line ID of User'),
        ),
    ]
